version: '3.8'

services:
  app:
    build: .
    image: autogen:latest
    container_name: autogen-app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DEBUG=False
      - ENV=production
      - API_VERSION=v1
      - API_PREFIX=/api
      - LOG_LEVEL=INFO
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - autogen-network

  nginx:
    image: nginx:alpine
    container_name: autogen-nginx
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./config/mcp-server.nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app
    networks:
      - autogen-network

networks:
  autogen-network:
    driver: bridge 